### PR TITLE
Feature/39 cascade question type test

### LINKED ISSUE #39: Cascade Question Type
## MVP Test cases

- [x] Should not show options when the data source is not set.
- [x] Should not be able to update values when options empty
- [x] Should have a parent dropdown.
- [x] Should have one or more child dropdowns.
- [x] Should depend on the selected option in the parent dropdown.
- [x] Should update child dropdowns when the selected option in the parent dropdown changes.

### PR DESCRIPTION
**Pull request by ifirmawan**
## TODO/DONE

- [x] TypeCascade Component
- [x] Load data source from sqlite file (currently : administrations.db)
- [x] Unit test
- [x] Download cascades files
- [x] Fix load cascades based form json

### Unit test list
- Should not show options when the data source is not set.
- Should not be able to update values when options empty
- Should have a parent dropdown.
- Should have one or more child dropdowns.
- Should depend on the selected option in the parent dropdown.
- Should update child dropdowns when the selected option in the parent dropdown changes.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204868663470098

### CODE REVIEW

**Review by dedenbangkit — CHANGES_REQUESTED** [review]
Please fix handle error if cascade is not selected based on the required level. Currently you can continue to the next question group / submit the cascade even we only select 1 level.

**Comment by ifirmawan** [comment]
> Please fix handle error if cascade is not selected based on the required level. Currently you can continue to the next question group / submit the cascade even we only select 1 level.

Resolved by this commit
https://github.com/akvo/nmis-mobile/pull/57/commits/26d14ff9bd5d7b71b5d0416568c81c253ec8917e
https://github.com/akvo/nmis-mobile/commit/26d14ff9bd5d7b71b5d0416568c81c253ec8917e
and here is the additional checklist :

- [x] Fix selected values based on the required level
- [x] Drop all cascades SQLite files after hitting the reset button

**Comment by dedenbangkit** [comment]
@ifirmawan how this 26d14ff commit solve the cascade issue? it's just test file, not implementation

**Comment by ifirmawan** [comment]
> @ifirmawan how this [26d14ff](https://github.com/akvo/nmis-mobile/commit/26d14ff9bd5d7b71b5d0416568c81c253ec8917e) commit solve the cascade issue? it's just test file, not implementation

oh sorry I mean 2 commits here mas @dedenbangkit 
https://github.com/akvo/nmis-mobile/commit/26d14ff9bd5d7b71b5d0416568c81c253ec8917e
https://github.com/akvo/nmis-mobile/pull/57/commits/8a707f13bf90c5cc81e1689815b1cde2a03494cb

**Review by dedenbangkit — APPROVED** [review]

**Pull request merged**
